name: Terraform CI

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
    paths:
      - "terraform/**"
      - ".github/workflows/deploy.yml"

env:
  TF_WORKING_DIR: terraform
  AWS_REGION: us-east-1

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::<ACCOUNT_ID>:role/github-actions-oidc
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: |
          terraform plan -input=false -out=tfplan
          terraform show -no-color tfplan > plan.txt

      - name: Comment PR with plan
        if: github.event_name == 'pull_request'
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            **Terraform Plan**
            ```diff
            ${{ steps.plan.outputs.stdout }}
            ```

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -input=false -auto-approve

      - name: Configure kubectl
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $(terraform output -raw cluster_name)

      - name: Deploy Kubernetes manifests
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          kubectl apply -f manifests/

      - name: Configure kubectl
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $(terraform output -raw cluster_name)

      - name: Deploy Kubernetes manifests
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: kubectl apply -f ../../manifests
