name: Deploy Infrastructure and Application

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

env:
  TF_WORKING_DIR: terraform
  AWS_REGION: eu-west-1
  TF_VAR_FILE: terraform.tfvars

permissions:
  id-token: write # required for assuming a role with OpenID Connect
  contents: read # required for actions/checkout
  pull-requests: write # required for adding comments to PRs with plan

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.0"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan (Pull Request)
        if: github.event_name == 'pull_request'
        id: plan
        run: |
          terraform plan -input=false -no-color -out=tfplan -var-file=../${{ env.TF_VAR_FILE }}

          # Create a human-readable summary
          echo "### Terraform Plan Summary" >> $GITHUB_STEP_SUMMARY
          echo "<details><summary>Click to expand</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```terraform' >> $GITHUB_STEP_SUMMARY
          terraform show -no-color tfplan >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY

      - name: Terraform Apply (Push to main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -input=false -auto-approve -var-file=../${{ env.TF_VAR_FILE }}

  kubernetes:
    name: Kubernetes
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform for outputs
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.0"

      - name: Terraform Init for Outputs
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name $(terraform -chdir="${{ env.TF_WORKING_DIR }}" output -raw cluster_name)
          kubectl version --client --short

      - name: Kubernetes Diff (Pull Request)
        if: github.event_name == 'pull_request'
        id: diff
        run: |
          # Use server-side dry run first, with a fallback to client-side diff
          DIFF_OUTPUT=$(kubectl diff -f k8s/ --server-dry-run=true 2>&1)
          EXIT_CODE=$?

          if [[ $EXIT_CODE -ne 0 && $EXIT_CODE -ne 1 ]]; then
            echo "Server-side dry run failed. Falling back to client-side diff."
            DIFF_OUTPUT=$(kubectl diff -f k8s/ 2>&1)
            EXIT_CODE=$?
          fi

          echo "### Kubernetes Diff" >> $GITHUB_STEP_SUMMARY
          echo "<details><summary>Click to expand</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```diff' >> $GITHUB_STEP_SUMMARY
          echo "$DIFF_OUTPUT" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY

          # Exit with an error only if the command failed for reasons other than finding a diff.
          # Exit code 1 means a diff was found, which is expected.
          if [[ $EXIT_CODE -ne 0 && $EXIT_CODE -ne 1 ]]; then
            exit $EXIT_CODE
          fi

      - name: Kubernetes Apply (Push to main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: kubectl apply -f k8s/
